language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-avalon-oniui' ]; then cd .. && eval "mv $currentfolder generator-avalon-oniui" && cd generator-avalon-oniui; fi
